### ISSUE TITLE
How to take one Information into another class

### ISSUE THREAD

**Issue by Admurai** [istdasschraeg/gaymmm#1]
public class Ironsmelter extends Industrie
{
    private int FineIron;
    
    private int Eisen;
    /**
     * Act - do whatever the Ironsmelter wants to do. This method is called whenever
     * the 'Act' or 'Run' button gets pressed in the environment.
     */
    public void Smellt100()
    {
    if (Eisen>99)
     {
        Eisen = ((Bohrer)getOneIntersectingObject(Bohrer.class)).getEisen();
         Eisen-=100;
        Greenfoot.delay(10);
        FineIron+=100;
        }

Why not working

**Comment by MoPaMo** [comment]
Yeah
